out_dir: results
metric_best: f1
wandb:
  use: True
  project: CustomProj
dataset:
  format: none
  name: custom
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode+MagLapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
  shuffle: False

posenc_MagLapPE:
  enable: True
  dim_pe: 32 # should be equal to 'd_model_aggr'
  
  # Config for magentic eigv.
  eigen:
    max_freqs: 50
  excl_k_eigenvectors: 1
  q: 0.25
  q_absolute: False
  symmetric_norm: False
  norm_comps_sep: False
  l2_norm: True
  sign_rotate: True

  # Config for MagLapNet
  d_model_elem: 2
  d_model_aggr: 32 # should be equal to 'dim_pe'
  num_heads: 1
  n_layers: 1
  dropout_p: 0.0
  return_real_output: True
  consider_im_part: True
  use_signnet: True
  use_gnn: False
  use_attention: False
  concatenate_eigenvalues: False
  norm: None

posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 1000
  model: Transformer
  dim_pe: 18
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
posenc_HKdiagSE:
  enable: False
  kernel:
    times_func: range(2,17)
  model: Linear
  dim_pe: 12
  raw_norm_type: BatchNorm
train:
  mode: custom #inference-only
  batch_size: 2
  eval_period: 5
  ckpt_period: 100
  ckpt_best: false
  #epoch_resume: 99 #
  #auto_resume: true
  #ckpt_clean: false
  #enable_ckpt: true
model:
  type: GPSModel
  loss_fun:  weighted_cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:  # Hyperparameters optimized for ~100k budget.
  layer_type: CustomGatedGCN+Performer
  layers: 8 # 14
  n_heads: 4
  dim_hidden: 32  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.1
  layer_norm: True
  batch_norm: False
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 32  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: False
  act: relu
  dropout: 0.1
  agg: sum
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adam
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 3000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
wandb:
  entity: alex97almunia
  name: ''
  project: gps2
  use: true
